#!/usr/bin/env bash

set -e

lint_synset() {
  xmllint --noout --schema "schemas/_lint.xsd" "$1"
}

cd "$(dirname "$0")/.."

if [ $# -eq 0 ]; then
  if [ -z "$CI" ]; then
    find synsets -type f -name "*.xml" -exec $0 {} \;
  fi
else
  for file in "$@"; do
    lint_synset "$file"
  done
fi

