
const shortPrefixes = {
  "adj.": "ADJ",
  "adv.": "ADV",
  "conj.": "CONJ",
  "f.": "NOUN",
  "f.indecl.": "NOUN",
  "f.pl.": "NOUN",
  "f.sg.": "NOUN",
  "intj.": "INTJ",
  "m.": "NOUN",
  "m./f.": "NOUN",
  "m.anim.": "NOUN",
  "m.indecl.": "NOUN",
  "m.pl.": "NOUN",
  "m.sg.": "NOUN",
  "n.": "NOUN",
  "n.indecl.": "NOUN",
  "n.pl.": "NOUN",
  "n.sg.": "NOUN",
  "num.": "NUM",
  "num.card.": "NUM",
  "num.coll.": "NUM",
  "num.diff.": "NUM",
  "num.fract.": "NUM",
  "num.mult.": "NUM",
  "num.ord.": "NUM",
  "num.subst.": "NUM",
  "particle": "PARTICLE",
  "phrase": "PHRASE",
  "prefix": "PREFIX",
  "prep.": "PREP",
  "prep. + gen.": "PREP",
  "pron.dem.": "PRON",
  "pron.indef.": "PRON",
  "pron.int.": "PRON",
  "pron.pers.": "PRON",
  "pron.poss.": "PRON",
  "pron.rec.": "PRON",
  "pron.refl.": "PRON",
  "pron.rel.": "PRON",
  "suffix": "SUFFIX",
  "v.aux. ipf.": "VERB",
  "v.aux. pf.": "VERB",
  "v.intr. ipf.": "VERB",
  "v.intr. ipf./pf.": "VERB",
  "v.intr. pf.": "VERB",
  "v.ipf.": "VERB",
  "v.pf.": "VERB",
  "v.refl. ipf.": "VERB",
  "v.refl. ipf./pf.": "VERB",
  "v.refl. pf.": "VERB",
  "v.tr. ipf.": "VERB",
  "v.tr. ipf./pf.": "VERB",
  "v.tr. pf.": "VERB"
};

const longPrefixes = {
  "adj.": "adjective",
  "adv.": "adverb",
  "conj.": "conjugation",
  "f.": "noun_f",
  "f.indecl.": "noun_f_indecl",
  "f.pl.": "noun_f_pl",
  "f.sg.": "noun_f_sg",
  "intj.": "interjection",
  "m.": "noun_m",
  "m./f.": "noun_m_f",
  "m.anim.": "noun_m_anim",
  "m.indecl.": "noun_m_indecl",
  "m.pl.": "noun_m_pl",
  "m.sg.": "noun_m_sg",
  "n.": "noun_n",
  "n.indecl.": "noun_n_indecl",
  "n.pl.": "noun_n_pl",
  "n.sg.": "noun_n_sg",
  "num.": "numeral",
  "num.card.": "numeral_card",
  "num.coll.": "numeral_coll",
  "num.diff.": "numeral_diff",
  "num.fract.": "numeral_fract",
  "num.mult.": "numeral_mult",
  "num.ord.": "numeral_ord",
  "num.subst.": "numeral_subst",
  "particle": "particle",
  "phrase": "phrase",
  "prefix": "prefix",
  "prep.": "preposition_",
  "prep. + gen.": "preposition_gen",
  "pron.dem.": "pronoun_dem",
  "pron.indef.": "pronoun_indef",
  "pron.int.": "pronoun_int",
  "pron.pers.": "pronoun_pers",
  "pron.poss.": "pronoun_poss",
  "pron.rec.": "pronoun_rec",
  "pron.refl.": "pronoun_refl",
  "pron.rel.": "pronoun_rel",
  "suffix": "suffix",
  "v.aux. ipf.": "verb_aux_ipf",
  "v.aux. pf.": "verb_aux_pf",
  "v.intr. ipf.": "verb_intr_ipf",
  "v.intr. ipf./pf.": "verb_intr_ipf_pf",
  "v.intr. pf.": "verb_intr_pf",
  "v.ipf.": "verb_ipf",
  "v.pf.": "verb_pf",
  "v.refl. ipf.": "verb_refl_ipf",
  "v.refl. ipf./pf.": "verb_refl_ipf_pf",
  "v.refl. pf.": "verb_refl_pf",
  "v.tr. ipf.": "verb_tr_ipf",
  "v.tr. ipf./pf.": "verb_tr_ipf_pf",
  "v.tr. pf.": "verb_tr_pf"
};

const abbreviations = {
  "adj.": "adjective",
  "adv.": "adverb",
  "conj.": "conjugation",
  "f.": "noun (feminine)",
  "f.indecl.": "noun (feminine, indeclinable)",
  "f.pl.": "noun (feminine, plural)",
  "f.sg.": "noun (feminine, single)",
  "intj.": "interjection",
  "m.": "noun (masculine)",
  "m./f.": "noun (masculine, feminine)",
  "m.anim.": "noun (masculine, animate)",
  "m.indecl.": "noun (masculine, indeclinable)",
  "m.pl.": "noun (masculine, plural)",
  "m.sg.": "noun (masculine, single)",
  "n.": "noun (neuter)",
  "n.indecl.": "noun (neuter, indeclinable)",
  "n.pl.": "noun (neuter, plural)",
  "n.sg.": "noun (neuter, single)",
  "num.": "numeral",
  "num.card.": "numeral (cardinal)",
  "num.coll.": "numeral (collective)",
  "num.diff.": "numeral (differential)",
  "num.fract.": "numeral (fractional)",
  "num.mult.": "numeral (multiplicative)",
  "num.ord.": "numeral (ordinal)",
  "num.subst.": "numeral (substantivised)",
  "particle": "particle",
  "phrase": "phrase",
  "prefix": "prefix",
  "prep.": "preposition",
  "prep. + gen.": "preposition (genitive)",
  "pron.dem.": "pronoun (demonstrative)",
  "pron.indef.": "pronoun (indefinite)",
  "pron.int.": "pronoun (intensive)",
  "pron.pers.": "pronoun (personal)",
  "pron.poss.": "pronoun (possesive)",
  "pron.rec.": "pronoun (reciprocal)",
  "pron.refl.": "pronoun (reflexive)",
  "pron.rel.": "pronoun (relative)",
  "suffix": "suffix",
  "v.aux. ipf.": "verb (auxiliary, imperfect)",
  "v.aux. pf.": "verb (auxiliary, perfect)",
  "v.intr. ipf.": "verb (intransitive, imperfect)",
  "v.intr. ipf./pf.": "verb (intransitive, imperfect, perfect)",
  "v.intr. pf.": "verb (intransitive, perfect)",
  "v.ipf.": "verb (imperfect)",
  "v.pf.": "verb (perfect)",
  "v.refl. ipf.": "verb (reflexive, imperfect)",
  "v.refl. ipf./pf.": "verb (reflexive, imperfect, perfect)",
  "v.refl. pf.": "verb (reflexive, perfect)",
  "v.tr. ipf.": "verb (transitive, imperfect)",
  "v.tr. ipf./pf.": "verb (transitive, imperfect, perfect)",
  "v.tr. pf.": "verb (transitive, perfect)"
};

function notFound(x) {
  throw new Error('Failed to find part of speech: ' + x);

}

module.exports = {
  disambiguate: (x) => abbreviations[x] || notFound(x),
  prefix: {
    short: (x) => shortPrefixes[x] || notFound(x),
    long: (x) => longPrefixes[x] || notFound(x),
  },
};
