name: Import from Google Sheets
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  pull:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [stable, beta]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: libxml install
        run: sudo apt-get install -y libxml2-utils --fix-missing

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Fetch synsets
        run: npx isv synsets pull
        env:
          ISV_BETA: ${{ matrix.branch != 'stable' && 'true' || 'false' }}
          ISV_DEBUG: 'true'
          ISV_ENCRYPTION_KEY: ${{ secrets.ISV_ENCRYPTION_KEY }}
          ISV_ENCRYPTION_IV: ${{ secrets.ISV_ENCRYPTION_IV }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}

      - name: Upload log file
        uses: actions/upload-artifact@v2
        with:
          name: database-engine-log
          path: isv-*.log

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: synsets
          message: 'synsets: import from new_interslavic_words_list'
          author_name: Medžuslovjansky Bot
          author_email: noreply@interslavic.fun
